# fly.toml app configuration file generated for lb-rust-web-hidden-haze-1593 on 2024-02-07T20:14:59+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lb-rust-web'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
