name: Deploy to fly.io
on:
    push:
        branches: [ "master" ]
    workflow_dispatch:

jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            
            - name: Install flyctl
              uses: superfly/flyctl-actions/setup-flyctl@master

            - name: Deploy to fly.io
              run: flyctl deploy --local-only
              env:
                FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
                GITHUB_ID: ${{ secrets.GITHUB_ID}}
                TOKEN: ${{ secrets.AUTOMATION_PAT}}